### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by leowla**
Updated the dependencies because why not.

### CODE REVIEW

**Comment by Androz2091** [comment]
Why not? Changing all dependencies is complicated, it is also necessary to update the bot code 
Unless you tested it?

**Comment by TrueWinter** [comment]
The version numbers on some of the updated dependencies could indicate a breaking change which would cause issues in the bot.
Unless you have properly tested every part of the bot and, if necessary, fixed broken code, I cannot merge this pull request.

**Comment by leowla** [comment]
I haven't tested every part of the bot, but I have fixed some things that weren't working.

I'll get back to you once i've tested everything.

**Comment by leowla** [comment]
I've tested most of the bot now, and nothing seems to be wrong with the code.
I know it will be kind of hard to take my word for it so I have the links to my Glitch project below.

https://ndt3update.glitch.me/
https://glitch.com/edit/#!/ndt3update

I won't be testing any more of the bot, my free time has gotten really short over the past week.

**Pull request closed without merging**
