### PR TITLE
Made some embeds

### PR DESCRIPTION
**Pull request by ghost**
Made embeds for some commands on my version of bot and wanted to give that code to you!

### CODE REVIEW

**Comment by TrueWinter** [comment]
Codacy (the code style checker that I use) doesn't like the code in this pull request due to missing semicolons.

**Comment by ghost** [comment]
...

**Comment by TrueWinter** [comment]
I use a service called Codacy to check the code style rules I use. A part of these code style rules I use is that lines must end with semicolons and the indent spaces should be tabs. These are the issues found by Codacy: [https://app.codacy.com/app/NdT3Development/DiscordBot/pullRequest?prid=1591174](https://app.codacy.com/app/NdT3Development/DiscordBot/pullRequest?prid=1591174)

**Comment by TrueWinter** [comment]
Thanks. Will merge now.

**Pull request merged**
